### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by archagy** [SonarCommunity/sonar-ndepend#1]
Hello I'd like to install this plugin for my sonarqube server. How ever which .jar did I have to move to the extensions folder ? the page says to move the sonar-ndepend-plugin-VERSION.jar but there are no file with that name.

Thanks in advance.

**Comment by archagy** [comment]
Okay I package the source code with mvn and got the  

> sonar-ndepend-plugin-1.0-Snapshot.jar

I added it to the extensions>plugins folder. 

Got the following error.

```
2019.09.26 13:03:07 WARN  web[][o.s.c.p.PluginLoader] API compatibility mode is no longer supported. In case of error, plugin NDepend [ndepend] should package its dependencies.
2019.09.26 13:05:22 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin NDepend [ndepend]
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:82)
        at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:543)
        at org.sonar.server.platform.Platform.start(Platform.java:211)
        at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:185)
        at org.sonar.server.platform.Platform.access$500(Platform.java:46)
        at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:371)
        at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
        at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:355)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
        at org.sonar.plugins.ndepend.NDependPlugin.getExtensions(NDependPlugin.java:46)
        at org.sonar.api.SonarPlugin.define(SonarPlugin.java:51)
        at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:72)
        ... 9 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
        at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
        at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
        ... 12 common frames omitted

```


is this plugin supported  by sonarqube ?
